[default_session]
startup_command = "nvim"

[[session]]
name = "Home ğŸ¡"
path = "~"
startup_command = "l"

[[session]]
name = "neovim config"
path = "~/.config/nvim"


[[session]]
name = "second brain ğŸ§ "
path = "~/sites/__obsidian/second-brain"
startup_command = "nvim"

[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"

